version: '3.9'

services:
  website:
    restart: unless-stopped
    image: labs:latest
    container_name: DoSALabs
    build: .
    ports:
      - 5556:80/tcp
  redis-dos:
    restart: unless-stopped
    image: redis:7.4.0-alpine
    container_name: DoSALabs-Redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 5516:6379/tcp
  postgresql-dos:
    restart: unless-stopped
    image: postgres:16.2-alpine3.19
    container_name: DoSALabs-Postgres
    environment:
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRES_PASSWORD=vlald
    ports:
      - 5526:5432/tcp
